[package]
name = "init-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
clam = { path = "../clam" }
log = { version = "0.4.26", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
